--------------------------------------------------------
--  Fichier créé - vendredi-février-17-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table UTILISATEUR
--------------------------------------------------------

  CREATE TABLE "P1906861"."UTILISATEUR" 
   (	"ID" NUMBER(*,0), 
	"USERNAME" VARCHAR2(255 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE), 
	"PERSO" NUMBER(*,0), 
	"SCORE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DUT" ;
--------------------------------------------------------
--  DDL for Index SYS_C00356008
--------------------------------------------------------

  CREATE UNIQUE INDEX "P1906861"."SYS_C00356008" ON "P1906861"."UTILISATEUR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DUT" ;
--------------------------------------------------------
--  DDL for Trigger AUTO_INCRE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "P1906861"."AUTO_INCRE" 
BEFORE INSERT ON UTILISATEUR
FOR EACH ROW
BEGIN 
    SELECT S_INCREMENT.NEXTVAL
    INTO :NEW.ID
    FROM DUAL;
END;

/
ALTER TRIGGER "P1906861"."AUTO_INCRE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTO_INCREMENT_USER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "P1906861"."AUTO_INCREMENT_USER" 
BEFORE INSERT ON UTILISATEUR
FOR EACH ROW
BEGIN
    select auto_increment_user.nextval INTO :new.id FROM DUAL;
END;
/
ALTER TRIGGER "P1906861"."AUTO_INCREMENT_USER" ENABLE;
--------------------------------------------------------
--  Constraints for Table UTILISATEUR
--------------------------------------------------------

  ALTER TABLE "P1906861"."UTILISATEUR" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "P1906861"."UTILISATEUR" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DUT"  ENABLE;
